repos:
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5  # Use the latest stable version of Bandit
    hooks:
      - id: bandit
        args: ["-r"]  # The "-r" flag ensures Bandit scans directories recursively
  