name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest coverage bandit pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Treat all other flake8 errors as warnings and continue
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run pytest with Coverage
        run: |
          # Run pytest and collect coverage data
          coverage run -m pytest --maxfail=1 --disable-warnings -q
          # Generate a coverage report in the terminal
          coverage report
          # Generate an XML coverage report for further analysis
          coverage xml
          # Generate an HTML coverage report
          coverage html
        continue-on-error: false

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov  # Upload the HTML coverage report folder

      - name: Enforce Coverage Threshold
        run: |
          # Fail the build if coverage is below the threshold (e.g., 80%)
          coverage report --fail-under=80

      - name: Run Bandit Security Scan
        run: |
          # Run Bandit recursively on the codebase with high severity and confidence
          bandit -r . -f json -o bandit-report.json

        continue-on-error: false  # Ensure the step fails if Bandit finds issues

      - name: Upload Bandit Report
        if: failure() || always()
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.json

      - name: Fail the build if Bandit found issues
        if: failure()
        run: |
          echo "Bandit detected high-severity or high-confidence issues. Failing the build."
          exit 1
