name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest bandit
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Treat all other flake8 errors as warnings and continue
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run Bandit Security Scan
        run: |
          # Run Bandit recursively on the codebase with high severity and confidence
          bandit -r . -f xml -o bandit-report.xml --severity-level HIGH --confidence-level HIGH

        continue-on-error: false  # Ensure the step fails if Bandit finds issues

      - name: Upload Bandit Report
        if: failure() || always()
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.xml

      - name: Fail the build if Bandit found issues
        if: failure()
        run: |
          echo "Bandit detected high-severity or high-confidence issues. Failing the build."
          exit 1
